### ISSUE TITLE
Create "carousel" component

### ISSUE THREAD

**Issue by gvn** [mozilla/mofo-ui#22]
<img width="559" alt="screen shot 2016-07-22 at 10 08 03 am" src="https://cloud.githubusercontent.com/assets/206379/17064965/3cc825cc-4ff4-11e6-9fea-9924dfc885e5.png">

Design: https://redpen.io/hy19242612b482d7ce

**Comment by gvn** [comment]
CC: @flukeout

**Comment by gvn** [comment]
@flukeout @sabrinang – I set up a demo of the component here:

https://gvn.github.io/mofo-ui/demo/

Feel free to give me notes in this ticket... 👌

**Comment by flukeout** [comment]
Right on, thanks! @sabrinang and I are both digging the way it adjusts to a narrower viewport.

And, if you're ready for detailed feedback...

* Place a blue background color behind the non-selected photos so that it shows through a bit when they are faded out
* Increase font size
* Pull out the quote marks into separate elements and place on either side of quote
* Change the font weights so that the quote body is lighter than the name of the person
* Change text alignment
  * Quote left aligned
  * Credit right aligned

We can adjust these as we build the site too though, so not urgent.

**Comment by gvn** [comment]
> Place a blue background color behind the non-selected photos so that it shows through a bit when they are faded out

This is what's currently being done, so maybe the background color just needs adjustment? The entire div has a blue bg and the photos opacity is reduced when they're not active.

> Increase font size

To what?

> Pull out the quote marks into separate elements and place on either side of quote

Can you provide the SVG for the mark?

> Change the font weights so that the quote body is lighter than the name of the person

K.


>Change text alignment
> Quote left aligned
> Credit right aligned

I tried this, but it doesn't look good for short quotes or instances where the last word on a line is too long and wraps. I think centering is going to work best...

**Comment by gvn** [comment]
Also, if you can provide the Sketch file it'd be much appreciated, @sabrinang

**Comment by gvn** [comment]
Basic component has been merged, but I'm going to leave this ticket open for design tweaks...

**Comment by flukeout** [comment]
That sounds good - I can make the style tweaks when I incorporate the new photos and content.

**Comment by flukeout** [comment]
Sounds good - I can make the adjustments when I add the content.

**Comment by sabrinang** [comment]
@gvn This mockup was previously done in illustrator - the link is here: https://drive.google.com/a/mozillafoundation.org/file/d/0B4Q8pzCpDS_eZ2ZnSlRVLS1CYm8/view

**Comment by gvn** [comment]
@flukeout It would be best to make as many necessary changes here in mofo-ui unless there's a compelling reason to make exceptions for Learning. Otherwise the component will be less consistent when we use it elsewhere...

**Comment by flukeout** [comment]
Oh yeah, I'll def make the changes in this repo.
