### ISSUE TITLE
Make the cursor look like pointer when hovered on radio filters

### ISSUE THREAD

**Issue by akshatnitd** [mozilla/mofo-ui#60]
Adding ```cursor: pointer;``` to the label of the radio filter will solve the issue. It will add to the UX greatly.

**Comment by akshatnitd** [comment]
@gvn Please have a look at the PR #61

**Comment by alanmoo** [comment]
I'm going through my open PRs today; I'll get to this

**Comment by akshatnitd** [comment]
@alanmoo Okay cool :+1:
