### ISSUE TITLE
MoFo footer - make icon a required element?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mofo-ui#63]
@gvn @alanmoo @kristinashu @sabrinang @Saallen @taisdesouzalessa 

Currently if you use the `<MofoFooter>` component from `mofo-ui` without specifying the [`iconType`](https://github.com/mozilla/mofo-ui/blob/master/src/components/mofo-footer/mofo-footer.jsx#L6) you'll get a warning saying that you forgot to pass a required prop. My question is, should we make the `iconType` a required prop or leave it optional? I checked out a few MoFo sites - Science, Pulse, Network, and Advocacy site all include icons in the footer section. The only exception I found (so far) is the [MozFest site](https://mozillafestival.org/). From the design perspective, do we want to force a more unified footer (must include icons) or leave room for flexibility?

**Comment by gvn** [comment]
I think we should push for a unified design and add icons to the MozFest site.

**Comment by mmmavis** [comment]
@gvn yea +1 on that!

**Comment by Saallen** [comment]
I support whatever y'all think is best here :)

**Comment by taisdesouzalessa** [comment]
I think we should make icons a required element in the footer so when users navigate through Mozilla properties they have the same experience.

**Comment by mmmavis** [comment]
Cool! Closing this ticket as there's no action to do on this repo. I will submit a PR on MozFest site repo to add icons to footer. 🎉
